### ISSUE TITLE
There is a bug if you click directly on the "Schedule" button

### ISSUE THREAD

**Issue by itxubfmh** [AlzheimerZA/RebootScheduleTimer#1]
It's almost perfect if you can't click on the 'Schedule' button without selecting a schedule from the drop-down menu. Thanks for the awsome coding. Hopefully the code can be improved.

you may refer to the error following:
You cannot call a method on a null-valued expression.
At C:\Users\itxubfmh\Downloads\Compressed\RebootScheduleTimer-main\RebootScheduleTimer.ps1:40 char:9
+     if (($combobox1.SelectedItem.ToString() -split ':')[0].length -lt ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

ERROR: Invalid syntax. Value expected for '/st'.
Type "SCHTASKS /CREATE /?" for usage.

**Comment by AlzheimerZA** [comment]
I have added a Warning pop-up when the Schedule button is clicked without selecting a schedule time.
You can change the wording of the Warning in line 46:
    $messageBoxMessage = "**Please select a Time from the combo box to schedule!**"
